controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mobile_base_controller:
      type: diff_drive_controller/DiffDriveController

    lift_controller_l: 
      type: position_controllers/JointGroupPositionController # for some reason the single joint controller doesn't work - so we use the group controller with a single joint #TODO: fix this
      interface_name: position
      joints: ["left_lift_joint"]
      pid:
        p: 5.0
        i: 20.0
        i_clamp: 100.0

    lift_controller_r: 
      type: position_controllers/JointGroupPositionController
      interface_name: position
      joints: ["right_lift_joint"]
      pid:
        p: 5.0
        i: 20.0
        i_clamp: 100.0
      

# -----------------------------------
mobile_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation : 0.445208
    wheel_radius : 0.0625

    # Publish rate
    publish_rate: 41.2               # this is what the real MiR platform publishes (default: 50)

lift_controller_l:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: ["left_lift_joint"]
    interface_name: position
    pid:
      p: 5.0
      i: 20.0
      i_clamp: 100.0

lift_controller_r:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: ["right_lift_joint"]
    interface_name: position
    pid:
      p: 5.0
      i: 20.0
      i_clamp: 100.0