# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: false # May lead to unexpectedly aborted goals with scaled JTC

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller
    - joint_trajectory_controller
    - joint_trajectory_controller_l
    - joint_trajectory_controller_r

  scaled_joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint


  joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: false
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  joint_trajectory_controller_l:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: false
    joints:
      - UR10_l/shoulder_pan_joint
      - UR10_l/shoulder_lift_joint
      - UR10_l/elbow_joint
      - UR10_l/wrist_1_joint
      - UR10_l/wrist_2_joint
      - UR10_l/wrist_3_joint

  joint_trajectory_controller_r:  
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: false
    joints:
      - UR10_r/shoulder_pan_joint
      - UR10_r/shoulder_lift_joint
      - UR10_r/elbow_joint
      - UR10_r/wrist_1_joint
      - UR10_r/wrist_2_joint
      - UR10_r/wrist_3_joint
