<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mir_launch_hardware</name>
  <version>0.1.0</version>
  <description>ROS 2 hardware bringup helpers for MiR robots</description>

  <maintainer email="match@ipa.fraunhofer.de">MATCH</maintainer>
  <license>BSD</license>

  <depend>geometry_msgs</depend>
  <depend>mir_driver</depend>
  <depend>mir_msgs</depend>
  <depend>mir_restapi</depend>
  <depend>mir_srvs</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2_ros</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
